version: "2"
services:
  app:
    build:
      context: ../
    volumes:
      - cache:/var/www/app/cache
      - ..:/var/www
    ports:
      - 8080:8080
    environment:
      - PHP_OPCACHE_ENABLE=0

  mysql:
    image: mysql
    volumes:
      - ../app/cache/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_RANDOM_ROOT_PASSWORD=1

  blackfire:
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN

  # Depdendency manager
  update:
    image: tico/composer
    command: ["update", "--no-dev", "--ignore-platform-reqs", "--no-ansi", "--no-interaction", "--no-progress", "--no-scripts", "-a", "-d", "/app"]
    volumes: ['..:/app']

  # Used for REST API or microservices
  phpunit:
    image: tico/phpunit
    command: ["--coverage-text","--coverage-html", "/app/tests/coverage", "--colors=never"]
    volumes: ['..:/app']

  # Used for REST API, microservices and fullstack
  codeception:
    image: codeception/codeception
    volumes: ['..:/project']

  # Used with codeception for UI (acceptance) testing
  selenium:
    image: selenium/standalone-chrome

volumes:
  cache:
    driver_opts:
      type: tmpfs
      device: tmpfs
