version: "2"
services:
  app:
    image: frameworkwtf/docker
    restart: always
    environment:
      APP_ENV: prod
      APP_RELEASE: RELEASE_PLACEHOLDER
      VIRTUAL_HOST: framework.wtf
      LETSENCRYPT_HOST: framework.wtf
      LETSENCRYPT_EMAIL: you@example.com
      VIRTUAL_PORT: 8080
  proxy:
    image: tico/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /tmp/certs:/etc/nginx/certs:ro
      - /tmp/vhost.d:/etc/nginx/vhost.d
      - /tmp/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /tmp/certs:/etc/nginx/certs
      - /tmp/vhost.d:/etc/nginx/vhost.d
      - /tmp/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy

  #mysql:
    #image: mysql:5.7
    #restart: always
    #volumes:
      #- ./data/mysql:/var/lib/mysql
    #environment:
      #- MYSQL_DATABASE=app
      #- MYSQL_USER=app
      #- MYSQL_PASSWORD=app
      #- MYSQL_RANDOM_ROOT_PASSWORD=1
